<<<<<<< HEAD
# Generated by Django 3.2.6 on 2021-10-29 17:54
=======
# Generated by Django 3.2.5 on 2021-10-21 13:48
>>>>>>> 6019f41c016fb3ae71ff4ca90e86f0a78662aec0

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        ('main', '0001_initial'),
=======
        ('main', '0005_alter_status_status'),
>>>>>>> 6019f41c016fb3ae71ff4ca90e86f0a78662aec0
    ]

    operations = [
        migrations.CreateModel(
            name='Mark',
            fields=[
<<<<<<< HEAD
                ('mark_id', models.IntegerField(primary_key=True, serialize=False)),
=======
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark_id', models.CharField(blank=True, max_length=250)),
>>>>>>> 6019f41c016fb3ae71ff4ca90e86f0a78662aec0
                ('date_added', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'mark',
                'ordering': ['date_added'],
            },
        ),
        migrations.CreateModel(
            name='MarkItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
                ('MainPost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.mainpost')),
<<<<<<< HEAD
                ('mark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mark.mark')),
=======
                ('mark', models.ForeignKey(db_column='mark_id', on_delete=django.db.models.deletion.CASCADE, to='mark.mark')),
>>>>>>> 6019f41c016fb3ae71ff4ca90e86f0a78662aec0
            ],
            options={
                'db_table': 'markitem',
            },
        ),
    ]
