# Generated by Django 3.2.6 on 2021-10-29 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('mark_id', models.IntegerField(primary_key=True, serialize=False)),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'mark',
                'ordering': ['date_added'],
            },
        ),
        migrations.CreateModel(
            name='MarkItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
                ('MainPost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.mainpost')),
                ('mark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mark.mark')),
            ],
            options={
                'db_table': 'markitem',
            },
        ),
    ]
