# Generated by Django 3.2.5 on 2021-10-21 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0005_alter_status_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark_id', models.CharField(blank=True, max_length=250)),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'mark',
                'ordering': ['date_added'],
            },
        ),
        migrations.CreateModel(
            name='MarkItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
                ('MainPost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.mainpost')),
                ('mark', models.ForeignKey(db_column='mark_id', on_delete=django.db.models.deletion.CASCADE, to='mark.mark')),
            ],
            options={
                'db_table': 'markitem',
            },
        ),
    ]
