<<<<<<< HEAD
# Generated by Django 3.2.6 on 2021-10-29 17:54

import ckeditor_uploader.fields
=======
# Generated by Django 3.2.5 on 2021-09-07 16:43

import ckeditor_uploader.fields
from django.conf import settings
>>>>>>> 6019f41c016fb3ae71ff4ca90e86f0a78662aec0
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
=======
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
>>>>>>> 6019f41c016fb3ae71ff4ca90e86f0a78662aec0
    ]

    operations = [
        migrations.CreateModel(
            name='chosunconsult',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, verbose_name='이름')),
<<<<<<< HEAD
                ('username', models.CharField(max_length=100, verbose_name='회원아이디')),
                ('phone_number', models.IntegerField()),
                ('university', models.CharField(blank=True, db_column='University', max_length=32, null=True)),
                ('contents', models.CharField(max_length=300, null=True, verbose_name='세부내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('status', models.CharField(default='상담대기', max_length=30, verbose_name='상담상태')),
=======
                ('phone_number', models.IntegerField()),
                ('university', models.CharField(blank=True, db_column='University', max_length=32, null=True)),
                ('contents', models.CharField(max_length=50, null=True, verbose_name='세부내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
>>>>>>> 6019f41c016fb3ae71ff4ca90e86f0a78662aec0
            ],
            options={
                'db_table': 'chosunconsult',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='mainconsult',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, verbose_name='이름')),
<<<<<<< HEAD
                ('username', models.CharField(max_length=100, verbose_name='회원아이디')),
                ('phone_number', models.IntegerField()),
                ('university', models.CharField(blank=True, db_column='University', max_length=32, null=True)),
                ('contents', models.CharField(max_length=300, null=True, verbose_name='세부내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('status', models.CharField(default='상담대기', max_length=30, verbose_name='상담상태')),
=======
                ('phone_number', models.IntegerField()),
                ('university', models.CharField(blank=True, db_column='University', max_length=32, null=True)),
                ('contents', models.CharField(max_length=50, null=True, verbose_name='세부내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
>>>>>>> 6019f41c016fb3ae71ff4ca90e86f0a78662aec0
            ],
            options={
                'db_table': 'mainconsult',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MainPost',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rogophoto', models.ImageField(blank=True, null=True, upload_to='', verbose_name='회사사진')),
                ('postname', models.CharField(max_length=50, verbose_name='회사명')),
                ('area', models.CharField(blank=True, max_length=10, null=True, verbose_name='근무지')),
                ('author', models.CharField(blank=True, max_length=16, verbose_name='작성자')),
                ('job', models.CharField(blank=True, max_length=10, null=True, verbose_name='직무')),
                ('etc', models.CharField(blank=True, max_length=30, null=True, verbose_name='우대사항')),
                ('ck', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='본문내용')),
                ('point_id', models.IntegerField(verbose_name='회사번호')),
            ],
            options={
                'db_table': 'main_post',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='member',
            fields=[
                ('id', models.CharField(blank=True, db_column='University', max_length=32, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=8)),
                ('author', models.CharField(max_length=16)),
                ('date', models.IntegerField()),
            ],
            options={
                'db_table': 'member',
                'managed': False,
            },
        ),
        migrations.CreateModel(
<<<<<<< HEAD
            name='Profile',
            fields=[
                ('nickname', models.CharField(max_length=64, verbose_name='닉네임')),
                ('phone_number', models.CharField(max_length=12, verbose_name='전화번호')),
                ('university', models.CharField(max_length=32, null=True, verbose_name='대학교')),
                ('profile_photo', models.ImageField(blank=True, upload_to='', verbose_name='프로필사진')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'main_profile',
                'managed': False,
            },
        ),
        migrations.CreateModel(
=======
>>>>>>> 6019f41c016fb3ae71ff4ca90e86f0a78662aec0
            name='seoulconsult',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, verbose_name='이름')),
<<<<<<< HEAD
                ('username', models.CharField(max_length=100, verbose_name='회원아이디')),
                ('phone_number', models.IntegerField()),
                ('university', models.CharField(blank=True, db_column='University', max_length=32, null=True)),
                ('contents', models.CharField(max_length=300, null=True, verbose_name='세부내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('status', models.CharField(default='상담대기', max_length=30, verbose_name='상담상태')),
=======
                ('phone_number', models.IntegerField()),
                ('university', models.CharField(blank=True, db_column='University', max_length=32, null=True)),
                ('contents', models.CharField(max_length=50, null=True, verbose_name='세부내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
>>>>>>> 6019f41c016fb3ae71ff4ca90e86f0a78662aec0
            ],
            options={
                'db_table': 'seoulconsult',
                'managed': False,
            },
        ),
        migrations.CreateModel(
<<<<<<< HEAD
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('상담완료', 'success'), ('상담실패', 'fail'), ('상담대0', 'wait')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
=======
>>>>>>> 6019f41c016fb3ae71ff4ca90e86f0a78662aec0
            name='chosunPost',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.mainpost')),
                ('rogophoto', models.ImageField(blank=True, null=True, upload_to='', verbose_name='회사사진')),
                ('postname', models.CharField(max_length=50, verbose_name='회사명')),
                ('area', models.CharField(blank=True, max_length=10, null=True, verbose_name='근무지')),
                ('author', models.CharField(blank=True, max_length=16, verbose_name='작성자')),
                ('job', models.CharField(blank=True, max_length=10, null=True, verbose_name='직무')),
                ('etc', models.CharField(blank=True, max_length=30, null=True, verbose_name='우대사항')),
                ('ck', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('point_id', models.IntegerField(default=1, verbose_name='회사번호')),
            ],
            options={
                'db_table': 'chosunPost',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='seoulPost',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.mainpost')),
                ('rogophoto', models.ImageField(blank=True, null=True, upload_to='', verbose_name='회사사진')),
                ('postname', models.CharField(max_length=50, verbose_name='회사명')),
                ('area', models.CharField(blank=True, max_length=10, null=True, verbose_name='근무지')),
                ('author', models.CharField(blank=True, max_length=16, verbose_name='작성자')),
                ('job', models.CharField(blank=True, max_length=10, null=True, verbose_name='직무')),
                ('etc', models.CharField(blank=True, max_length=30, null=True, verbose_name='우대사항')),
                ('ck', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('point_id', models.IntegerField(default=2, verbose_name='회사번호')),
            ],
            options={
                'db_table': 'seoulPost',
                'managed': False,
            },
        ),
<<<<<<< HEAD
=======
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('nickname', models.CharField(max_length=64, verbose_name='닉네임')),
                ('phone_number', models.CharField(max_length=12, verbose_name='전화번호')),
                ('university', models.CharField(max_length=32, null=True, verbose_name='대학교')),
                ('profile_photo', models.ImageField(blank=True, upload_to='', verbose_name='프로필사진')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
>>>>>>> 6019f41c016fb3ae71ff4ca90e86f0a78662aec0
    ]
