# Generated by Django 3.2.5 on 2021-09-09 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_profile_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profile',
            table='main_profile',
        ),
    ]
