# Generated by Django 3.2.5 on 2021-10-24 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_status_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(choices=[('상담완료', 'success'), ('상담실패', 'fail'), ('상담대기', 'wait')], max_length=20),
        ),
    ]
